### ISSUE TITLE
How to run a trained model

### ISSUE THREAD

**Issue by kreattang** [StanfordVL/mini_behavior#11]
May I ask how to load a trained model and run it in mini_behavior env?

**Comment by JiahengHu** [comment]
Depends on how you are training your model. If you are using stable-baselines3, for example, you can simply run `model = PPO.load(CKPT_NAME, env=env)`, where CKPT_NAME is the name of your checkpoint.

**Comment by kreattang** [comment]
Thanks for your reply.
